### ISSUE TITLE
Build ToDo List (basic)

### ISSUE THREAD

**Issue by bradcammon** [bradcammon/to-do-it#4]
The ToDo list should have the following functionality:
- [x] grow dynamically, with new items added to the end/bottom of the list
- [x] each item should be able to be marked as completed, with both its state (data) and styling reflecting the change
- [x] each item should be editable
- [x] each item should be able to be deleted.  Deleted items should be removed from the list immediately.

All changes to the list of toDo items should be kept in sync with the backend.
